Module7 task2
htmlacademy-javascript/1045709-kekstagram-27 pull request #6
Opened 2022-10-09 12:19 UTC by Samefral

2022-10-09 14:32 UTC, pavel-nyukalo requested changes

2022-10-09 14:32 UTC, pavel-nyukalo commented on js/popup.js
> +    document.removeEventListener('keydown', popupCloseKeydownHandler);
Код 14-16 и 21-23 дублирует 1:1, можно вынести его в функцию, а тут и в `popupCloseClickHandler` вызывать уже

2022-10-09 14:32 UTC, pavel-nyukalo commented on js/popup.js
> +    </li>`;
Тут может не пройти по критерию

![image](https://user-images.githubusercontent.com/52506235/194762394-9b4a6245-60cf-4f25-9435-fd8f6e07a874.png)

Поскольку `avatar, name, message` можно считать внешними данными

2022-10-09 14:32 UTC, pavel-nyukalo commented on js/popup.js
> +};
Вот это очень хорошее решение 👍🏻 

Единственное, я бы `+picture..` заменил на `Number(picture...)`, т.к `+` можно визуально не заметить при рефакторинге например

2022-10-09 16:51 UTC, Samefral commented
Заметил, что при появлении popup добавляются 2 обработчика для закрытия, которые удаляют сами себя, значит при закрытии второй обработчик остается, не знаю как исправить без function declaration

2022-10-10 13:07 UTC, pavel-nyukalo requested changes

2022-10-10 13:07 UTC, pavel-nyukalo commented on js/popup.js
> +  document.addEventListener('keydown', popupCloseKeydownHandler);
Тут какая ситуация возникает:
мы открываем попап, добавляем два обработчика. Но при закрытии попапа мы удаляем только один обработчик (в зависимости как закрыли). То есть на при закрытии тоже надо удалять оба.

Для решения [допустимо](https://up.htmlacademy.ru/javascript/27/criteries#d5) декларативное объявление, поскольку нам нужно "всплытие"

2022-10-11 12:48 UTC, pavel-nyukalo approved these changes

2022-10-11 12:48 UTC, merged