uploading comments function added
htmlacademy-javascript/1045709-kekstagram-27 pull request #8
Opened 2022-10-22 12:06 UTC by Samefral

2022-10-22 12:49 UTC, Samefral commented
Не знаю как удалить обработчик загрузки комментариев после закрытия попапа. Добавил обработчик через onclick, потому что при каждом открытии попапа добавляется уже существующий обработчик.

2022-10-23 17:18 UTC, pavel-nyukalo requested changes

2022-10-23 17:18 UTC, pavel-nyukalo commented on js/photo-popup.js
> +    };
Для решения проблемы с удалением обработчика можно навешивать (и удалять) обработчики в `showPopup`. А комментарии передавать параметром отсюда. Это как наименьшее из возможных решений

2022-10-26 07:10 UTC, pavel-nyukalo approved these changes

2022-10-26 07:10 UTC, merged